workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        integrations:
            app_store_connect: CodeMagic
        environment:
            ios_signing:
                distribution_type: app_store  
                bundle_identifier: com.missionyr.tworoom
            flutter: stable
        scripts:
            - name: Set up code signing settings on Xcode project
              script: | 
                xcode-project use-profiles
            - name: Clean
              script: |
                flutter pub cache repair
            - name: list up
              script: |
                ls                       
            - name: Get Flutter packages
              script: | 
                 flutter pub get
            - name: Install pods
              script: | 
                find . -name "Podfile" -execdir pod install /;
            - name: Flutter build ipa
              script: | 
                flutter build ipa --release /
                --build-name=1.0.0 /
                --export-options-plist=/Users/builder/export_options.plist
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - flutter_drive.log
        publishing:
           email:
                recipients:
                    - terasawawaaa@gmail.com
                notify:
                  success: true
                  failure: true
           app_store_connect:
              auth: integration
              submit_to_testflight: true
              beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
                - group name 1
              submit_to_app_store: false